### ISSUE TITLE
The DateTimeLocalInput module will pass values that will be rejected by Chrome

### ISSUE THREAD

**Issue by Poundex** [apache/groovy-geb#194]
Chrome is very strict when directly setting the value of a date/time input. It will accept the format `YYYY-MM-dd'T'HH:mm[:ss[.SSS]]` and nothing else. A date/time string with any more precision than this will not be truncated, but vetoed with an error that will be logged by the console:
![chrome_datetime](https://github.com/user-attachments/assets/545df0d6-a349-4c50-a6c0-fe5591f7eadc)
but not communicated to the driver in any way, meaning that from the test's point of view a requested change has simply not happened. 

This module exposes two methods for setting the value of the input, one that takes a String and one that takes a LocalDateTime. The one that takes a String passes the value straight through without any validation or processing. This will succeed if it matches Chrome's expected format, and fail (silently) if it doesn't - even if it is a perfectly valid ISO8601 date/time string.
The method that takes a LocalDateTime passes the toString value. If the LocalDateTime instance was constructed with `LocalDateTime.now()` then this will behave differently after Java 9. Before Java 9 `LocalDateTime.now()` had millisecond precision, and so a `toString()` call would match Chrome's expected format. But after Java 9 it has nanosecond precision, and so the extra digits in the fraction-of-second part would cause the set value to be rejected by Chrome.

**Comment by jonnybot0** [comment]
This was fixed by df7d709, so I think we can safely close it.
